/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.cadastro;

import Model.bean.Cliente;
import Model.bean.Divida;
import Model.bean.Pessoa;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author vitor
 */
public class CadDivida extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadDivida
     */
    private static CadDivida instancia  = null;
    public ArrayList<Integer>registros;
     public ArrayList<Cliente> registroslistaCliente;
    public CadDivida() {
        initComponents();
        Divida divida = new Divida();
        this.getTxtCodigoDivida().setEditable(false);
        for(Cliente clientes : divida.obterClientes()){
            this.getSlcCredor().addItem(clientes.getNomeCliente());
            this.getSlcDevedor().addItem(clientes.getNomeCliente());
        }
    }

    public static CadDivida getInstancia() {
        if(instancia == null)
            instancia = new CadDivida();
        
        return instancia;
    }

    public static void setInstancia(CadDivida instancia) {
        CadDivida.instancia = instancia;
    }

    public JButton getBtnSalvarDivida() {
        return btnSalvarDivida;
    }

    public void setBtnSalvarDivida(JButton btnSalvarDivida) {
        this.btnSalvarDivida = btnSalvarDivida;
    }


    public JLabel getjLabel7() {
        return lblTitulo;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.lblTitulo = jLabel7;
    }

    public JLabel getLblCodigo() {
        return lblCodigo;
    }

    public void setLblCodigo(JLabel lblCodigo) {
        this.lblCodigo = lblCodigo;
    }

    public JLabel getLblCredor() {
        return lblCredor;
    }

    public void setLblCredor(JLabel lblCredor) {
        this.lblCredor = lblCredor;
    }

    public JLabel getLblData() {
        return lblData;
    }

    public void setLblData(JLabel lblData) {
        this.lblData = lblData;
    }

    public JLabel getLblDevedor() {
        return lblDevedor;
    }

    public void setLblDevedor(JLabel lblDevedor) {
        this.lblDevedor = lblDevedor;
    }

   

    public JLabel getLblDivida() {
        return lblDivida;
    }

    public void setLblDivida(JLabel lblDivida) {
        this.lblDivida = lblDivida;
    }

    public JComboBox<String> getSlcCredor() {
        return slcCredor;
    }

    public JButton getBtnLimpar() {
        return btnLimpar;
    }

    public void setBtnLimpar(JButton btnLimpar) {
        this.btnLimpar = btnLimpar;
    }

    public JLabel getBtnPdocumento() {
        return btnPdocumento;
    }

    public void setBtnPdocumento(JLabel btnPdocumento) {
        this.btnPdocumento = btnPdocumento;
    }

    public JButton getBtnPesquisar() {
        return btnPesquisar;
    }

    public void setBtnPesquisar(JButton btnPesquisar) {
        this.btnPesquisar = btnPesquisar;
    }

    public JFormattedTextField getTxtPdocumento() {
        return txtPdocumento;
    }

    public void setTxtPdocumento(JFormattedTextField txtPdocumento) {
        this.txtPdocumento = txtPdocumento;
    }

    public void setSlcCredor(JComboBox<String> slcCredor) {
        this.slcCredor = slcCredor;
    }

    public JComboBox<String> getSlcDevedor() {
        return slcDevedor;
    }

    public void setSlcDevedor(JComboBox<String> slcDevedor) {
        this.slcDevedor = slcDevedor;
    }

    public JTextField getTxtCodigoDivida() {
        return txtCodigoDivida;
    }

    public void setTxtCodigoDivida(JTextField txtCodigoDivida) {
        this.txtCodigoDivida = txtCodigoDivida;
    }

    public JFormattedTextField getTxtDataAtualizacao() {
        return txtDataAtualizacao;
    }

    public void setTxtDataAtualizacao(JFormattedTextField txtDataAtualizacao) {
        this.txtDataAtualizacao = txtDataAtualizacao;
    }

    public JTextField getTxtDivida() {
        return txtDivida;
    }

    public void setTxtDivida(JTextField txtDivida) {
        this.txtDivida = txtDivida;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        slcCredor = new javax.swing.JComboBox<>();
        txtDataAtualizacao = new javax.swing.JFormattedTextField();
        lblDevedor = new javax.swing.JLabel();
        txtCodigoDivida = new javax.swing.JTextField();
        lblData = new javax.swing.JLabel();
        btnSalvarDivida = new javax.swing.JButton();
        lblDivida = new javax.swing.JLabel();
        slcDevedor = new javax.swing.JComboBox<>();
        lblTitulo = new javax.swing.JLabel();
        txtDivida = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        lblCredor = new javax.swing.JLabel();
        txtPdocumento = new javax.swing.JFormattedTextField();
        btnPdocumento = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 153, 255));
        setClosable(true);
        setIconifiable(true);

        try {
            txtDataAtualizacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblDevedor.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblDevedor.setForeground(new java.awt.Color(0, 0, 0));
        lblDevedor.setText("Devedor:");

        txtCodigoDivida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoDividaActionPerformed(evt);
            }
        });

        lblData.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblData.setForeground(new java.awt.Color(0, 0, 0));
        lblData.setText("Data de atualização:");

        btnSalvarDivida.setBackground(new java.awt.Color(0, 102, 204));
        btnSalvarDivida.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvarDivida.setText("Salvar");
        btnSalvarDivida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarDividaActionPerformed(evt);
            }
        });

        lblDivida.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblDivida.setForeground(new java.awt.Color(0, 0, 0));
        lblDivida.setText("Dívida:");

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Cadastrar Dívida");

        txtDivida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDividaActionPerformed(evt);
            }
        });

        lblCodigo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCodigo.setForeground(new java.awt.Color(0, 0, 0));
        lblCodigo.setText("Código:");

        lblCredor.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCredor.setForeground(new java.awt.Color(0, 0, 0));
        lblCredor.setText("Credor:");

        try {
            txtPdocumento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnPdocumento.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnPdocumento.setForeground(new java.awt.Color(0, 0, 0));
        btnPdocumento.setText("Documento:");

        btnPesquisar.setBackground(new java.awt.Color(0, 102, 204));
        btnPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarpesquisarCpfCliente(evt);
            }
        });

        btnLimpar.setBackground(new java.awt.Color(153, 153, 153));
        btnLimpar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparpesquisarCpfCliente(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(255, 0, 0));
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluircadastrarCliente(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDataAtualizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(slcDevedor, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDivida, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDivida))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCredor)
                            .addComponent(slcCredor, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtPdocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPdocumento)
                            .addComponent(txtCodigoDivida, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCodigo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblData)
                                .addGap(189, 189, 189)
                                .addComponent(lblDevedor))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSalvarDivida, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 115, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitulo)
                    .addGap(0, 227, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(btnPdocumento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPdocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar)
                    .addComponent(btnLimpar))
                .addGap(18, 18, 18)
                .addComponent(lblCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigoDivida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCredor)
                    .addComponent(lblDivida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(slcCredor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDivida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDevedor)
                    .addComponent(lblData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDataAtualizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slcDevedor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarDivida, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 12, Short.MAX_VALUE)
                    .addComponent(lblTitulo)
                    .addGap(0, 355, Short.MAX_VALUE)))
        );

        setBounds(392, 81, 522, 436);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoDividaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoDividaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoDividaActionPerformed

    private void btnSalvarDividaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarDividaActionPerformed
        try {
            // TODO add your handling code here:
            Divida divida = new Divida();
            divida.setIdDivida(Integer.parseInt(this.getTxtCodigoDivida().getText().equals("") ? "0" : this.getTxtCodigoDivida().getText()));
            
            String formato = "dd/MM/yyyy";
            Date data = new SimpleDateFormat(formato).parse(this.getTxtDataAtualizacao().getText());
            Pessoa credorPessoa = new Pessoa();
            Pessoa devedorPessoa = new Pessoa();
            credorPessoa.setNomePessoa(this.getSlcCredor().getSelectedItem().toString());
            devedorPessoa.setNomePessoa(this.getSlcDevedor().getSelectedItem().toString());
            divida.setCredor(credorPessoa);
            divida.setDevedor(devedorPessoa);
            String valor = this.getTxtDivida().getText().replace(".", "");
            valor = valor.replace(",",".");
            divida.setValorDivida(Double.parseDouble(valor));
            divida.setDataAtualizacao(data);
            if(this.getTxtCodigoDivida().getText().equals("")){
                divida.inserir();
            }else{
                try {
                    divida.alterar();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarDividaActionPerformed

    private void txtDividaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDividaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDividaActionPerformed

    private void btnPesquisarpesquisarCpfCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarpesquisarCpfCliente
        // TODO add your handling code here:         
        Divida divida = new Divida();
        String documento = this.getTxtPdocumento().getText().replace(".","");
        documento = documento.replace("-", "");
        for(Divida dv : divida.consultar(documento) ){
            this.getTxtCodigoDivida().setText(Integer.toString(dv.getIdDivida()));
             SimpleDateFormat  formatador  =  new SimpleDateFormat("dd/MM/yyyy");
            this.getTxtDataAtualizacao().setText(formatador.format(dv.getDataAtualizacao()));
            this.getTxtDivida().setText(Double.toString(dv.getValorDivida()).replace(".",","));
            this.getSlcCredor().setSelectedItem(dv.getCredor().getNomePessoa());
            this.getSlcDevedor().setSelectedItem(dv.getDevedor().getNomePessoa());
        }
        if(this.getTxtCodigoDivida().getText().equals("")){
            this.getBtnSalvarDivida().setText("Salvar");
            this.getLblTitulo().setText("Cadastrar Dívida");
        }else{
            this.getBtnSalvarDivida().setText("Alterar");
            this.getLblTitulo().setText("Alterar Dívida");
        }
    }//GEN-LAST:event_btnPesquisarpesquisarCpfCliente

    

    private void btnLimparpesquisarCpfCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparpesquisarCpfCliente
        // TODO add your handling code here:
        
        this.getTxtCodigoDivida().setEditable(false);
        
        this.getTxtCodigoDivida().setText("");
        this.getTxtDataAtualizacao().setText("");
        this.getTxtDivida().setText("");
        this.getTxtPdocumento().setText("");
        this.getSlcCredor().setSelectedItem("Vitor França");
         this.getSlcDevedor().setSelectedItem("Vitor França");
         this.getBtnSalvarDivida().setText("Salvar");
         this.getLblTitulo().setText("Cadastrar Dívida");
    }//GEN-LAST:event_btnLimparpesquisarCpfCliente

    public JLabel getLblTitulo() {
        return lblTitulo;
    }

    public void setLblTitulo(JLabel lblTitulo) {
        this.lblTitulo = lblTitulo;
    }

    private void btnExcluircadastrarCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluircadastrarCliente
        // TODO add your handling code here:
       Divida divida = new Divida();
        try {
            divida.excluir(Integer.parseInt(this.getTxtCodigoDivida().getText()));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluircadastrarCliente

    public JButton getBtnExcluir() {
        return btnExcluir;
    }

    public void setBtnExcluir(JButton btnExcluir) {
        this.btnExcluir = btnExcluir;
    }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JLabel btnPdocumento;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvarDivida;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCredor;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblDevedor;
    private javax.swing.JLabel lblDivida;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JComboBox<String> slcCredor;
    private javax.swing.JComboBox<String> slcDevedor;
    private javax.swing.JTextField txtCodigoDivida;
    private javax.swing.JFormattedTextField txtDataAtualizacao;
    private javax.swing.JTextField txtDivida;
    private javax.swing.JFormattedTextField txtPdocumento;
    // End of variables declaration//GEN-END:variables
}
