/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.cadastro;

import Model.bean.Divida;
import Model.bean.Pagamento;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author vitor
 */
public class CadPagamento extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadPagamento
     */
    private static CadPagamento instancia  = null;

    public static CadPagamento getInstancia() {
        if(instancia == null)
            instancia = new CadPagamento();
        
        return instancia;
    }

    public static void setInstancia(CadPagamento instancia) {
        CadPagamento.instancia = instancia;
    }

    public JButton getBtnSalvarPagamento() {
        return btnSalvarPagamento;
    }

    public void setBtnSalvarPagamento(JButton btnSalvarPagamento) {
        this.btnSalvarPagamento = btnSalvarPagamento;
    }



    public JLabel getjLabel7() {
        return lblTitulo;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.lblTitulo = jLabel7;
    }

    public JLabel getLblCodPag() {
        return lblDevedor;
    }

    public void setLblCodPag(JLabel lblCodPag) {
        this.lblDevedor = lblCodPag;
    }

    public JLabel getLblDataAtu() {
        return lblDataAtu;
    }

    public void setLblDataAtu(JLabel lblDataAtu) {
        this.lblDataAtu = lblDataAtu;
    }

    public JLabel getLblDataPag() {
        return lblDataPag;
    }

    public void setLblDataPag(JLabel lblDataPag) {
        this.lblDataPag = lblDataPag;
    }

    public JLabel getLblDivida() {
        return lblDivida;
    }

    public void setLblDivida(JLabel lblDivida) {
        this.lblDivida = lblDivida;
    }

    public JLabel getLblValorDivida() {
        return lblValorDivida;
    }

    public void setLblValorDivida(JLabel lblValorDivida) {
        this.lblValorDivida = lblValorDivida;
    }

    public JLabel getLblValorPg() {
        return lblValorPg;
    }

    public void setLblValorPg(JLabel lblValorPg) {
        this.lblValorPg = lblValorPg;
    }

    public JTextField getTxtCodigoPagamento() {
        return txtCodigoPagamento;
    }

    public void setTxtCodigoPagamento(JTextField txtCodigoPagamento) {
        this.txtCodigoPagamento = txtCodigoPagamento;
    }

    public JTextField getTxtDataAtu() {
        return txtDataAtu;
    }

    public void setTxtDataAtu(JTextField txtDataAtu) {
        this.txtDataAtu = txtDataAtu;
    }

    public JTextField getTxtDataPg() {
        return txtDataPg;
    }

    public void setTxtDataPg(JTextField txtDataPg) {
        this.txtDataPg = txtDataPg;
    }

    public JTextField getTxtDivida() {
        return txtDivida;
    }

    public void setTxtDivida(JTextField txtDivida) {
        this.txtDivida = txtDivida;
    }

    public JFormattedTextField getTxtValor() {
        return txtValor;
    }

    public void setTxtValor(JFormattedTextField txtValor) {
        this.txtValor = txtValor;
    }

    public JFormattedTextField getTxtvalorDivida() {
        return txtvalorDivida;
    }

    public void setTxtvalorDivida(JFormattedTextField txtvalorDivida) {
        this.txtvalorDivida = txtvalorDivida;
    }
    
    public CadPagamento() {
        initComponents();
        this.getTxtCodigoPagamento().setEditable(false);
        this.getTxtCredor().setEditable(false);
        this.getTxtDevedor().setEditable(false);
        this.getTxtDivida().setEditable(false);
        this.getTxtvalorDivida().setEditable(false);
        this.getTxtDataAtu().setEditable(false);
        
    }

    public JFormattedTextField getTxtPdocumento() {
        return txtPdocumento;
    }

    public void setTxtPdocumento(JFormattedTextField txtPdocumento) {
        this.txtPdocumento = txtPdocumento;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtvalorDivida = new javax.swing.JFormattedTextField();
        lblDataPag = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        btnSalvarPagamento = new javax.swing.JButton();
        lblValorDivida = new javax.swing.JLabel();
        lblDataAtu = new javax.swing.JLabel();
        lblDevedor = new javax.swing.JLabel();
        txtCodigoPagamento = new javax.swing.JTextField();
        txtDataAtu = new javax.swing.JTextField();
        lblValorPg = new javax.swing.JLabel();
        txtDivida = new javax.swing.JTextField();
        lblDivida = new javax.swing.JLabel();
        txtDataPg = new javax.swing.JTextField();
        txtValor = new javax.swing.JFormattedTextField();
        btnExcluir = new javax.swing.JButton();
        txtDevedor = new javax.swing.JTextField();
        txtCredor = new javax.swing.JTextField();
        lblCodPag1 = new javax.swing.JLabel();
        lblCredor = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        txtPdocumento = new javax.swing.JFormattedTextField();
        btnPdocumento = new javax.swing.JLabel();
        slcAcao = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(102, 153, 255));
        setClosable(true);
        setIconifiable(true);

        txtvalorDivida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        lblDataPag.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblDataPag.setForeground(new java.awt.Color(0, 0, 0));
        lblDataPag.setText("Data de pagemento:");

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Realizar Pagamento");

        btnSalvarPagamento.setBackground(new java.awt.Color(0, 102, 204));
        btnSalvarPagamento.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvarPagamento.setText("Salvar");
        btnSalvarPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarPagamentoActionPerformed(evt);
            }
        });

        lblValorDivida.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblValorDivida.setForeground(new java.awt.Color(0, 0, 0));
        lblValorDivida.setText("Valor da dívida:");

        lblDataAtu.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblDataAtu.setForeground(new java.awt.Color(0, 0, 0));
        lblDataAtu.setText("Data de atualização:");

        lblDevedor.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblDevedor.setForeground(new java.awt.Color(0, 0, 0));
        lblDevedor.setText("Devedor");

        txtCodigoPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoPagamentoActionPerformed(evt);
            }
        });

        txtDataAtu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataAtuActionPerformed(evt);
            }
        });

        lblValorPg.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblValorPg.setForeground(new java.awt.Color(0, 0, 0));
        lblValorPg.setText("Valor a ser pago:");

        txtDivida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDividaActionPerformed(evt);
            }
        });

        lblDivida.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblDivida.setForeground(new java.awt.Color(0, 0, 0));
        lblDivida.setText("Dívida:");

        txtDataPg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataPgActionPerformed(evt);
            }
        });

        txtValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtValorKeyPressed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(255, 0, 0));
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluircadastrarCliente(evt);
            }
        });

        txtDevedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDevedorActionPerformed(evt);
            }
        });

        txtCredor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCredorActionPerformed(evt);
            }
        });

        lblCodPag1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCodPag1.setForeground(new java.awt.Color(0, 0, 0));
        lblCodPag1.setText("Código:");

        lblCredor.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCredor.setForeground(new java.awt.Color(0, 0, 0));
        lblCredor.setText("Credor");

        btnLimpar.setBackground(new java.awt.Color(153, 153, 153));
        btnLimpar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparpesquisarCpfCliente(evt);
            }
        });

        btnPesquisar.setBackground(new java.awt.Color(0, 102, 204));
        btnPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarpesquisarCpfCliente(evt);
            }
        });

        try {
            txtPdocumento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnPdocumento.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnPdocumento.setForeground(new java.awt.Color(0, 0, 0));
        btnPdocumento.setText("Documento:");

        slcAcao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pagar", "Alterar" }));
        slcAcao.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                slcAcaoItemStateChanged(evt);
            }
        });
        slcAcao.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                slcAcaoPropertyChange(evt);
            }
        });
        slcAcao.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                slcAcaoVetoableChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(67, 67, 67))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtvalorDivida, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDataAtu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtValor)
                            .addComponent(txtDataPg)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDataPag)
                                    .addComponent(lblValorPg))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCodPag1))
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDivida)
                            .addComponent(txtDivida)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDevedor)
                        .addGap(243, 243, 243)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCredor)
                            .addComponent(txtCredor)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDevedor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSalvarPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblValorDivida)
                            .addComponent(lblDataAtu)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPdocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(slcAcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(btnPesquisar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpar))
                            .addComponent(btnPdocumento))
                        .addGap(0, 27, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblTitulo)
                .addGap(8, 8, 8)
                .addComponent(btnPdocumento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPdocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar)
                    .addComponent(btnLimpar)
                    .addComponent(slcAcao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodPag1)
                    .addComponent(lblDivida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDivida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataAtu)
                    .addComponent(lblDataPag))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDataPg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataAtu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorDivida)
                    .addComponent(lblValorPg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtvalorDivida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCredor)
                    .addComponent(lblDevedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDevedor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCredor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        setBounds(392, 81, 528, 537);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarPagamentoActionPerformed
        // TODO add your handling code here:
        Pagamento pagamento = new Pagamento();
       Divida div = new Divida();
        div.getIdDivida();
        div.getCredor().setNomePessoa();
        div.get
       pagamento.getDivida().setIdDivida(Integer.parseInt(this.getTxtDivida().getText()));
        pagamento.setIdpag(Integer.parseInt(this.getTxtCodigoPagamento().getText().equals("") ? "0" : this.getTxtCodigoPagamento().getText()));
        String valor = this.getTxtValor().getText().replace(".", "");
        valor = valor.replace(",", ".");
        pagamento.setValorpago(Double.parseDouble(valor));
        String divida = this.getTxtvalorDivida().getText().replace(".", "");
        divida = divida.replace(",", ".");
        pagamento.getDivida().setValorDivida(Double.parseDouble(divida));
        SimpleDateFormat formatar = new SimpleDateFormat("dd/MM/yyyy");
        try {
            pagamento.setData_pagamento(formatar.parse(this.getTxtDataPg().getText()));
            pagamento.getDivida().setDataAtualizacao(formatar.parse(this.getTxtDataAtu().getText()));
        } catch (ParseException ex) {
            Logger.getLogger(CadPagamento.class.getName()).log(Level.SEVERE, null, ex);
        }
        //Converter para duas casas decimais
        DecimalFormatSymbols x = new DecimalFormatSymbols();
        x.setDecimalSeparator('.');
        DecimalFormat decimalForm = new DecimalFormat("##.##", x);
        //Verificar  a data de atualização 
        long diferenca = ((pagamento.getDivida().getDataAtualizacao().getTime() - pagamento.getData_pagamento().getTime()) + 3600000) / 86400000L;
        if (diferenca < 0) {
            double multa = (pagamento.getDivida().getValorDivida() + (pagamento.getDivida().getValorDivida() * 2 / 100));
    
            double juros = multa + (multa * (Math.abs(diferenca) * 0.35) / 100);
            System.out.println("Juros " + juros);
            pagamento.getDivida().setValorDivida(Double.parseDouble(decimalForm.format(juros)));
            this.getTxtvalorDivida().setText(String.valueOf(decimalForm.format(juros)));
        }
        if(this.getTxtDataPg().getText().equals("")){
            try {
                pagamento.realizarPagamento(pagamento);
            } catch (ParseException ex) {
                Logger.getLogger(CadPagamento.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(CadPagamento.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            pagamento.alterarPagamento(pagamento);
        }
    }//GEN-LAST:event_btnSalvarPagamentoActionPerformed

    private void txtCodigoPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoPagamentoActionPerformed

    private void txtDataAtuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataAtuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataAtuActionPerformed

    private void txtDividaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDividaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDividaActionPerformed

    private void txtDataPgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataPgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataPgActionPerformed

    private void txtValorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorKeyPressed
        

    }//GEN-LAST:event_txtValorKeyPressed

    public JTextField getTxtCredor() {
        return txtCredor;
    }

    public void setTxtCredor(JTextField txtCredor) {
        this.txtCredor = txtCredor;
    }

    public JTextField getTxtDevedor() {
        return txtDevedor;
    }

    public void setTxtDevedor(JTextField txtDevedor) {
        this.txtDevedor = txtDevedor;
    }

    private void btnExcluircadastrarCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluircadastrarCliente
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnExcluircadastrarCliente

    private void txtDevedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDevedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDevedorActionPerformed

    private void txtCredorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCredorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCredorActionPerformed

    private void btnLimparpesquisarCpfCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparpesquisarCpfCliente
        // TODO add your handling code here:

    }//GEN-LAST:event_btnLimparpesquisarCpfCliente

    private void btnPesquisarpesquisarCpfCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarpesquisarCpfCliente
        // TODO add your handling code here:
        Pagamento pagamento = new Pagamento();
        String documento = this.getTxtPdocumento().getText().replace(".","");
        documento = documento.replace("-", "");
        if(this.getSlcAcao().getSelectedItem().equals("Pagar")){
            this.getLblTitulo().setText("Realizar Pagamento");
            this.btnSalvarPagamento.setText("Salvar");
            for(Divida dv :pagamento.obterDividas(documento)){               
                this.getTxtCredor().setText(dv.getCredor().getNomePessoa());
                this.getTxtDevedor().setText(dv.getDevedor().getNomePessoa());
                SimpleDateFormat  formatador  =  new SimpleDateFormat("dd/MM/yyyy");
                this.getTxtDataAtu().setText(formatador.format(dv.getDataAtualizacao()));
                this.getTxtDivida().setText(Integer.toString(dv.getIdDivida()));               
                String divida = Double.toString(dv.getValorDivida());
                divida = divida.replace(".", ","); 
                this.getTxtvalorDivida().setText(divida);
            }
        }else{
            this.getLblTitulo().setText("Alterar Pagamento");
            this.btnSalvarPagamento.setText("Alterar");
            for(Pagamento pg :pagamento.buscarPorDocumento(documento)){
                this.getTxtCodigoPagamento().setText(Integer.toString(pg.getIdpag()));
                this.getTxtCredor().setText(pg.getDivida().getCredor().getNomePessoa());
                this.getTxtDevedor().setText(pg.getDivida().getDevedor().getNomePessoa());
                SimpleDateFormat  formatador  =  new SimpleDateFormat("dd/MM/yyyy");
                this.getTxtDataAtu().setText(formatador.format(pg.getDivida().getDataAtualizacao()));
                this.getTxtDivida().setText(Integer.toString(pg.getDivida().getIdDivida()));
                String valor =Double.toString(pg.getValorpago()); 
                valor = valor.replace(".", ",");
                String divida = Double.toString(pg.getDivida().getValorDivida());
                divida = divida.replace(".", ","); 
                this.getTxtvalorDivida().setText(divida);
                this.getTxtValor().setText(valor);
            } 
        }
        
       
    }//GEN-LAST:event_btnPesquisarpesquisarCpfCliente

    public JLabel getLblTitulo() {
        return lblTitulo;
    }

    public void setLblTitulo(JLabel lblTitulo) {
        this.lblTitulo = lblTitulo;
    }

    public JComboBox<String> getSlcAcao() {
        return slcAcao;
    }

    public void setSlcAcao(JComboBox<String> slcAcao) {
        this.slcAcao = slcAcao;
    }

    private void slcAcaoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_slcAcaoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_slcAcaoItemStateChanged

    private void slcAcaoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_slcAcaoPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_slcAcaoPropertyChange

    private void slcAcaoVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_slcAcaoVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_slcAcaoVetoableChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JLabel btnPdocumento;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvarPagamento;
    private javax.swing.JLabel lblCodPag1;
    private javax.swing.JLabel lblCredor;
    private javax.swing.JLabel lblDataAtu;
    private javax.swing.JLabel lblDataPag;
    private javax.swing.JLabel lblDevedor;
    private javax.swing.JLabel lblDivida;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblValorDivida;
    private javax.swing.JLabel lblValorPg;
    private javax.swing.JComboBox<String> slcAcao;
    private javax.swing.JTextField txtCodigoPagamento;
    private javax.swing.JTextField txtCredor;
    private javax.swing.JTextField txtDataAtu;
    private javax.swing.JTextField txtDataPg;
    private javax.swing.JTextField txtDevedor;
    private javax.swing.JTextField txtDivida;
    private javax.swing.JFormattedTextField txtPdocumento;
    private javax.swing.JFormattedTextField txtValor;
    private javax.swing.JFormattedTextField txtvalorDivida;
    // End of variables declaration//GEN-END:variables
}
