/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.table;

import Model.bean.Divida;
import Model.bean.DividaTableModel;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JTable;

/**
 *
 * @author vitor
 */
public class DividaTable extends javax.swing.JInternalFrame {

    /**
     * Creates new form DividaTable
     */
    private static DividaTable instancia  = null;

    public static DividaTable getInstancia() {
        if(instancia == null)
            instancia = new DividaTable();
        
        return instancia;
    }

    public static void setInstancia(DividaTable instancia) {
        DividaTable.instancia = instancia;
    }
    public DividaTable() {
        initComponents();
        Divida dividaBean = new Divida();
        DividaTableModel dividaTm = new DividaTableModel(this);
        dividaTm.popularTabela(dividaBean.listarDivida());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAtualizar = new javax.swing.JButton();
        lblCpf = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JFormattedTextField();
        btnPesquisar = new javax.swing.JButton();
        slcFiltro = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaDivida = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 153, 255));
        setClosable(true);
        setIconifiable(true);
        setTitle("Lista Dívida");

        btnAtualizar.setBackground(new java.awt.Color(0, 102, 204));
        btnAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        lblCpf.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCpf.setForeground(new java.awt.Color(0, 0, 0));
        lblCpf.setText("Documento:");

        try {
            txtDocumento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnPesquisar.setBackground(new java.awt.Color(0, 102, 204));
        btnPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        slcFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas", "Pagas", "Não pagas" }));
        slcFiltro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                slcFiltroItemStateChanged(evt);
            }
        });
        slcFiltro.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                slcFiltroPropertyChange(evt);
            }
        });
        slcFiltro.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                slcFiltroVetoableChange(evt);
            }
        });

        tabelaDivida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código dívida", "Devedor", "Documento ", "Valor dívida", "Credor", "Data atualização"
            }
        ));
        jScrollPane1.setViewportView(tabelaDivida);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Consultar Dívida");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCpf)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(slcFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(263, 263, 263))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCpf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slcFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );

        setBounds(192, 21, 822, 561);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:
        Divida dividaBean = new Divida();
        DividaTableModel dividaTm = new DividaTableModel(this);
        dividaTm.popularTabela(dividaBean.listarDivida());
        this.getSlcFiltro().setSelectedItem("Todas");
        this.getTxtDocumento().setText("");
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
        Divida divida = new Divida();
        DividaTableModel dividaTm = new DividaTableModel(this);
        
         String cpfFormatado = this.getTxtDocumento().getText().replace("-","");
        cpfFormatado = cpfFormatado.replace(".","");   
        dividaTm.popularTabela(divida.buscarDevedorCPF(cpfFormatado, this.getSlcFiltro().getSelectedItem().toString()));
        
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void slcFiltroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_slcFiltroItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_slcFiltroItemStateChanged

    private void slcFiltroPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_slcFiltroPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_slcFiltroPropertyChange

    private void slcFiltroVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_slcFiltroVetoableChange
        // TODO add your handling code here:

    }//GEN-LAST:event_slcFiltroVetoableChange

    public JComboBox<String> getSlcFiltro() {
        return slcFiltro;
    }

    public void setSlcFiltro(JComboBox<String> slcFiltro) {
        this.slcFiltro = slcFiltro;
    }

    public JTable getTabelaDivida() {
        return tabelaDivida;
    }

    public void setTabelaDivida(JTable tabelaDivida) {
        this.tabelaDivida = tabelaDivida;
    }

    public JFormattedTextField getTxtDocumento() {
        return txtDocumento;
    }

    public void setTxtDocumento(JFormattedTextField txtDocumento) {
        this.txtDocumento = txtDocumento;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JComboBox<String> slcFiltro;
    private javax.swing.JTable tabelaDivida;
    private javax.swing.JFormattedTextField txtDocumento;
    // End of variables declaration//GEN-END:variables
}
